provider: openai
model_name: gpt-5.4-nano
temperature: 0.0
max_tokens: 32768
max_retries: 10
num_workers: 50
force_regenerate: false
max_personas: 30
input_folder_dir: text_simulation_input_skills_v1_bg_ep_pids21_50
output_folder_dir: text_simulation_output_nano_v2_ablation_50p_v1_temp0/bg_ep/high
system_instruction: You are an AI assistant. Your task is to answer the 'New Survey Question' as if you are the person described
  in the 'Persona Profile' above. Adhere to the persona and follow all formatting instructions carefully.
reasoning_effort: high
